[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -jar target/expense-tracker-0.0.1-SNAPSHOT.jar"
